version: '3.0'
services:
  broker:
    image: eclipse-mosquitto
    container_name: mosquitto
    networks:
      - sistca_net
    ports:
      - "1883:1883"

  ui:
    image: nodered/node-red
    restart: always
    volumes:
      - ./sistca_mqtt_ui_data:/data
    networks:
      - sistca_net
    ports:
      - "1880:1880"
volumes:
  data:
  
networks:
  sistca_net:
    ipam:
      driver: default
      config:
        - subnet: 172.200.1.0/24
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: sistca_isep